"""add MediaKind Enum

Revision ID: 2306c9e1f5b3
Revises: 1f3453e03664
Create Date: 2026-04-28 20:30:36.139270

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2306c9e1f5b3"
down_revision: Union[str, Sequence[str], None] = "1f3453e03664"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("media_files", sa.Column("storage_key", sa.Text(), nullable=False))
    op.create_unique_constraint(None, "media_files", ["storage_key"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "media_files", type_="unique")
    op.drop_column("media_files", "storage_key")
    # ### end Alembic commands ###
