"""initial migration

Revision ID: 4ef4f0f2ae0a
Revises: b0f572a36d6c
Create Date: 2026-04-28 19:48:42.633650

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4ef4f0f2ae0a"
down_revision: Union[str, Sequence[str], None] = "b0f572a36d6c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "employees",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("full_name", sa.Text(), nullable=False),
        sa.Column("photo_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["photo_id"], ["media_files.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("employees")
    # ### end Alembic commands ###
