"""initial migration

Revision ID: b0f572a36d6c
Revises: 
Create Date: 2026-04-28 19:47:53.949314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0f572a36d6c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('public_url', sa.Text(), nullable=True),
    sa.Column('mime_type', sa.Text(), nullable=False),
    sa.Column('kind', sa.Enum('image', 'video', name='media_kind'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media_files')
    # ### end Alembic commands ###
